name: BatesPlugin
version: 0.3.3
main: com.batesy.BatesPlugin
api-version: "1.21"

commands:
  grief:
    description: Enable/Disable Mob Griefing (does not affect damage)
    usage: /grief <mob> [true|false]
    permission: batesplugin.grief
  skib:
    description: ...
    usage: ...
  bates:
    description: Main command
    permission: batesplugin.manage

permissions:
  batesplugin.grief:
    description: Enable/Disable Mob Griefing (does not affect damage)
    default: op
  batesplugin.manage:
    description: Manage plugin (such as reloading config)
    default: op
