name: BatesPlugin
version: 0.3.1
main: com.batesy.BatesPlugin
api-version: "1.20"

commands:
  creepergrief:
    description: Enable/Disable Creeper Block Griefing (does not affect damage)
    usage: /creepergrief on|off
    permission: batesplugin.creepergrief
    aliases: [cg, creepergriefing]
  skib:
    description: ...
    usage: ...
  bates:
    description: Main command
    permission: batesplugin.manage

permissions:
  batesplugin.creepergrief:
    description: Enable/Disable Creeper Block Griefing (does not affect damage)
    default: op
  batesplugin.manage:
    description: Manage plugin (such as reloading config)
    default: op
